# Local clock
[[clocks]]
name = "ğŸ’»"

# At home
[[clocks]]
name = "ğŸ "
tz = "Europe/Berlin"

# Costa Rica
[[clocks]]
name = "ğŸŒ´"
tz = "America/Costa_Rica"

# New York (EST)
[[clocks]]
name = "ğŸ—½"
tz = "America/New_York"

